
version: '3.8'


services:
  api:
    
    build: .
    
    ports:
      - "4000:4000"
    
    environment:
      MONGODB_URI: mongodb://mongo:27017/trabajadoresdb
    depends_on:
      - mongo

  
  mongo:
    
    image: mongo:5.0
   
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
