# Generated by Django 5.2.7 on 2025-10-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
