# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import vehiculo_pb2 as vehiculo__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vehiculo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VehiculoServiceStub(object):
    """El servicio gRPC que expondrá el microservicio de Vehiculos.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerificarDisponibilidad = channel.unary_unary(
                '/vehiculo.VehiculoService/VerificarDisponibilidad',
                request_serializer=vehiculo__pb2.VehiculoRequest.SerializeToString,
                response_deserializer=vehiculo__pb2.DisponibilidadResponse.FromString,
                _registered_method=True)


class VehiculoServiceServicer(object):
    """El servicio gRPC que expondrá el microservicio de Vehiculos.
    """

    def VerificarDisponibilidad(self, request, context):
        """Define un método (RPC) llamado VerificarDisponibilidad.
        Recibe un mensaje VehiculoRequest y devuelve un mensaje DisponibilidadResponse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VehiculoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerificarDisponibilidad': grpc.unary_unary_rpc_method_handler(
                    servicer.VerificarDisponibilidad,
                    request_deserializer=vehiculo__pb2.VehiculoRequest.FromString,
                    response_serializer=vehiculo__pb2.DisponibilidadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vehiculo.VehiculoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vehiculo.VehiculoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VehiculoService(object):
    """El servicio gRPC que expondrá el microservicio de Vehiculos.
    """

    @staticmethod
    def VerificarDisponibilidad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vehiculo.VehiculoService/VerificarDisponibilidad',
            vehiculo__pb2.VehiculoRequest.SerializeToString,
            vehiculo__pb2.DisponibilidadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
