# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vehiculo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vehiculo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0evehiculo.proto\x12\x08vehiculo\"&\n\x0fVehiculoRequest\x12\x13\n\x0bvehiculo_id\x18\x01 \x01(\t\",\n\x16\x44isponibilidadResponse\x12\x12\n\ndisponible\x18\x01 \x01(\x08\x32k\n\x0fVehiculoService\x12X\n\x17VerificarDisponibilidad\x12\x19.vehiculo.VehiculoRequest\x1a .vehiculo.DisponibilidadResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vehiculo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VEHICULOREQUEST']._serialized_start=28
  _globals['_VEHICULOREQUEST']._serialized_end=66
  _globals['_DISPONIBILIDADRESPONSE']._serialized_start=68
  _globals['_DISPONIBILIDADRESPONSE']._serialized_end=112
  _globals['_VEHICULOSERVICE']._serialized_start=114
  _globals['_VEHICULOSERVICE']._serialized_end=221
# @@protoc_insertion_point(module_scope)
